//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        public int idArchivo { get; set; }
        public string pathArchivo { get; set; }
        public Nullable<int> idPublicacion { get; set; }
        public Nullable<int> idMensaje { get; set; }
    
        public virtual Mensaje Mensaje { get; set; }
        public virtual Publicacion Publicacion { get; set; }
    }
}
