//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public Grupo()
        {
            this.Publicacions = new HashSet<Publicacion>();
            this.Tareas = new HashSet<Tarea>();
            this.Usuarios = new HashSet<Usuario>();
            this.UsuarioSubGrupoes = new HashSet<UsuarioSubGrupo>();
        }
    
        public int idGrupo { get; set; }
        public string nombreGrupo { get; set; }
        public string nombreSubGrupo { get; set; }
        public Nullable<int> idPertenencia { get; set; }
    
        public virtual ICollection<Publicacion> Publicacions { get; set; }
        public virtual ICollection<Tarea> Tareas { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
        public virtual ICollection<UsuarioSubGrupo> UsuarioSubGrupoes { get; set; }
    }
}
