//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public Grupo()
        {
            this.Publicacions = new HashSet<Publicacion>();
            this.Tareas = new HashSet<Tarea>();
            this.Usuarios = new HashSet<Usuario>();
            this.UsuarioSubGrupoes = new HashSet<UsuarioSubGrupo>();
        }
    
        public int idGrupo { get; set; }
        public string nombreGrupo { get; set; }
        public string nombreSubGrupo { get; set; }
        public Nullable<int> idPertenencia { get; set; }
    
        public virtual ICollection<Publicacion> Publicacions { get; set; }
        public virtual ICollection<Tarea> Tareas { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
        public virtual ICollection<UsuarioSubGrupo> UsuarioSubGrupoes { get; set; }
    }
}
