//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public Mensaje()
        {
            this.Archivoes = new HashSet<Archivo>();
        }
    
        public int idMensaje { get; set; }
        public string path { get; set; }
        public int idEnvia { get; set; }
        public int idRecibe { get; set; }
    
        public virtual ICollection<Archivo> Archivoes { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
