//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public Mensaje()
        {
            this.Archivoes = new HashSet<Archivo>();
        }
    
        public int idMensaje { get; set; }
        public string path { get; set; }
        public int idEnvia { get; set; }
        public int idRecibe { get; set; }
    
        public virtual ICollection<Archivo> Archivoes { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
