//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POIEntities : DbContext
    {
        public POIEntities()
            : base("name=POIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Archivo> Archivoes { get; set; }
        public DbSet<Grupo> Grupoes { get; set; }
        public DbSet<Mensaje> Mensajes { get; set; }
        public DbSet<Publicacion> Publicacions { get; set; }
        public DbSet<Tarea> Tareas { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<UsuarioSubGrupo> UsuarioSubGrupoes { get; set; }
    }
}
