//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POIEntities : DbContext
    {
        public POIEntities()
            : base("name=POIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Archivo> Archivoes { get; set; }
        public DbSet<Grupo> Grupoes { get; set; }
        public DbSet<Mensaje> Mensajes { get; set; }
        public DbSet<Publicacion> Publicacions { get; set; }
        public DbSet<Tarea> Tareas { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<UsuarioSubGrupo> UsuarioSubGrupoes { get; set; }
    }
}
