//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        public Publicacion()
        {
            this.Archivoes = new HashSet<Archivo>();
        }
    
        public int idPublicacion { get; set; }
        public string publicacion1 { get; set; }
        public int idGrupo { get; set; }
        public int idUsuario { get; set; }
    
        public virtual ICollection<Archivo> Archivoes { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
