//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int idTarea { get; set; }
        public string tarea1 { get; set; }
        public bool status { get; set; }
        public int idGrupo { get; set; }
    
        public virtual Grupo Grupo { get; set; }
    }
}
