//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Mensajes = new HashSet<Mensaje>();
            this.Mensajes1 = new HashSet<Mensaje>();
            this.Publicacions = new HashSet<Publicacion>();
            this.UsuarioSubGrupoes = new HashSet<UsuarioSubGrupo>();
        }
    
        public int idUsuario { get; set; }
        public string correo { get; set; }
        public string contrasenia { get; set; }
        public int idGrupo { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual ICollection<Mensaje> Mensajes { get; set; }
        public virtual ICollection<Mensaje> Mensajes1 { get; set; }
        public virtual ICollection<Publicacion> Publicacions { get; set; }
        public virtual ICollection<UsuarioSubGrupo> UsuarioSubGrupoes { get; set; }
    }
}
