//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Mensajes = new HashSet<Mensaje>();
            this.Mensajes1 = new HashSet<Mensaje>();
            this.Publicacions = new HashSet<Publicacion>();
            this.UsuarioSubGrupoes = new HashSet<UsuarioSubGrupo>();
        }
    
        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string correo { get; set; }
        public string contrasenia { get; set; }
        public int idGrupo { get; set; }
        public string ip { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual ICollection<Mensaje> Mensajes { get; set; }
        public virtual ICollection<Mensaje> Mensajes1 { get; set; }
        public virtual ICollection<Publicacion> Publicacions { get; set; }
        public virtual ICollection<UsuarioSubGrupo> UsuarioSubGrupoes { get; set; }
    }
}
